PACKAGE_NAME := DroidGuardHelper
PACKAGE_ID   := org.microg.gms.droidguard

ifeq ($(RELEASE), stable)
VERSION_NAME := 0.1.0
VERSION_CODE := 4
else
VERSION_NAME := 0.1.0-10-gf64bf69
VERSION_CODE := 14
endif


include ../microg.defs.mk
