PACKAGE_NAME := GmsFrameworkProxy
PACKAGE_ID   := com.google.android.gsf
PRIV_APP     := true

# there's no preview release for this package
VERSION_NAME := 0.1.0
VERSION_CODE := 8


include ../microg.defs.mk
