PACKAGE_NAME := FakeStore
PACKAGE_ID   := com.android.vending

ifeq ($(RELEASE), stable)
VERSION_NAME := 0.0.1
VERSION_CODE := 1
else
VERSION_NAME := 0.0.2
VERSION_CODE := 16
endif


include ../microg.defs.mk
