PACKAGE_NAME := GmsCore
PACKAGE_ID   := com.google.android.gms
PRIV_APP     := true

ifeq ($(RELEASE), stable)
VERSION_NAME := 0.2.4
VERSION_CODE := 9258259
else
VERSION_NAME := 0.2.4-111-gf1cdb48
VERSION_CODE := 122221403
endif


include ../microg.defs.mk
